### PR TITLE
Update some new function in Liquidsoap <2.04

### PR DESCRIPTION
**Pull request by tobycm**
Just some that I found along the way of scripting

### CODE REVIEW

**Comment by vittee** [comment]
Thanks for the PR, I didn't even know that someone is actually using my extension 👍🏻

**Comment by tobycm** [comment]
It's awesome xD

**Comment by vittee** [comment]
I'm going to release it to VS Code Marketplace soon.

In the mean time, if you're intersted in Liquidsoap, my new [project](https://github.com/vittee/medley) may interest you.
It is a NodeJS library for playing music seamlessly in which I'm planning to use it for my own Discord server and my own internet/pirate radio.

**Comment by tobycm** [comment]
I was looking at it yesterday but have no idea what that is 😂

Thanks for the extension anyway ♥

**Pull request merged**
